export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_FAILED = 'FETCH_FAILED';
export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const FETCH_INGREDIENTS_REQUEST = 'FETCH_INGREDIENTS_REQUEST';
export const FETCH_INGREDIENTS_SUCCESS = 'FETCH_INGREDIENTS_SUCCESS';
export const SET_ORDERS = 'SET_ORDERS';
export const PURCHASE_ORDER_START = 'PURCHASE_ORDER_START'
export const PURCHASE_ORDER_SUCCESS = 'PURCHASE_ORDER_SUCCESS'
export const PURCHASE_ORDER_FAILED = 'PURCHASE_ORDER_FAILED'
export const PURCHASE_ORDER_INIT = 'PURCHASE_ORDER_INIT'

